CREATE TABLE Accounts (
    Id INT NOT NULL AUTO_INCREMENT,
    Title VARCHAR(255) NOT NULL,
    UserId INT NOT NULL,
    Currency ENUM('BGN', 'EUR') NOT NULL,
    Balance FLOAT NOT NULL,
    PRIMARY KEY(Id),
    FOREIGN KEY(UserId) REFERENCES Users(Id)
    ON UPDATE CASCADE ON DELETE CASCADE,
    UNIQUE KEY UserIdAndTitle (UserId, Title)
)