CREATE TABLE Sessions(
    Id VARCHAR(255) NOT NULL,
    UserId INT NOT NULL,
    CreatedOn TIMESTAMP NOT NULL,
    ExpiresAt TIMESTAMP NOT NULL DEFAULT '2038-01-19 03:14:07',
    PRIMARY KEY(Id),
    FOREIGN KEY(UserId) REFERENCES Users(Id)
    ON UPDATE CASCADE ON DELETE CASCADE,
    UNIQUE KEY UserIdAndCreatedOn (UserId, CreatedOn)
)