CREATE TABLE Users(
    Id INT NOT NULL AUTO_INCREMENT,
    Username VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Salt VARCHAR(255) NOT NULL,
    Balance FLOAT NOT NULL DEFAULT 0,
    PRIMARY KEY(Id)
)
